### ISSUE TITLE
Inconsistency in score

### ISSUE THREAD

**Issue by sivagollapalli** [joshsoftware/code-curiosity#115]
PFA
![total_score](https://cloud.githubusercontent.com/assets/280199/18469352/833144ee-79c5-11e6-8dec-14b185c92b7e.png)

In the attachment, if you see total scores show as 5 points but whereas featured groups and user dashboard doesn't show updated score. Currently it show as 3 points.

**Comment by SagareGanesh** [comment]
@sivagollapalli I think this happens because of time gap between rake tasks. Please see [shedule.rb](https://github.com/joshsoftware/code-curiosity/blob/master/config/schedule.rb) file. As per shedule.rb _**Auto score**_ activity happens at 3.00 am and _**Update score**_ activity happens at 6.00 am(According to  production server timezone). 
Thanks

**Comment by sivagollapalli** [comment]
Is there any specific reason for the time gap between Auto Score and Update score ? I think we should update immediately or we have to provide some message to let the user know about this. Otherwise,  same misunderstanding might happen? Thoughts please?

**Comment by gautamrege** [comment]
We cannot update immediately -- Scoring happens on commits and activites in parallel, it is not done user-wise. Hence we have to wait for commit & activities (and in future Pull Request tasks) to complete before the user score can be updated. 

Hence the inconsistency in score update. Not making a change in this process now unless we see serious issues arising from this. Hope this clarifies.
