### ISSUE TITLE
Commits/Activities of the last day of month are assigned to next round

### ISSUE THREAD

**Issue by BandanaPandey** [joshsoftware/code-curiosity#141]
Currently for each round last day commits and activities are displayed on the next round's activities and commits list, which according to me should not happen.

![contribution](https://cloud.githubusercontent.com/assets/16642417/19030143/75940980-8969-11e6-9299-621b96e996de.png)

Thoughts?

**Comment by prasadsurase** [comment]
This doesn't happen for everyone and for every round. It's because the [CommitsFetcher](https://github.com/joshsoftware/code-curiosity/blob/master/app/models/commits_fetcher.rb#L57) and the [ActivitiesFetcher](https://github.com/joshsoftware/code-curiosity/blob/master/app/models/activities_fetcher.rb#L41) which run on 1st of every month are assigned the latest open round, but are fetching the data for the previous month's last day, hereby assigning the wrong round.

this can be fixed by two ways: 1) Check if the job is running on first then assign the old round. 2) Find round from the date of the activity and assign it.
