### ISSUE TITLE
[critical] User who deletes his account and signs-up again gets all Royalty points again! 

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/code-curiosity#149]
LoL -- we mature and learn on the fly! We have just had our first case of a user deleting his account and signing up again. All his royalty points were restored and the user has made a redemption request again! 

Scenario: 
-  User signs up
- Gets royalty points 
- Send redemption request
- Deletes own account
- Signs up again 
- Gets all royalty points back again.
- Redeems the _same_ points again!! 

Need urgent fix!

**Comment by prasadsurase** [comment]
@gautamrege When the user destroys his account, we are modifying the uid to append '-DELETED'. When the user re-signups using the same account, we arent able to find the existing account using uid because the uid has been modified. Hence, a new user is created with the same data(email, uid, provider etc). Also, we dont have validation for uniqueness of uid. The culprits for the errors
are [User.from_omniauth](https://github.com/joshsoftware/code-curiosity/blob/master/app/models/user.rb#L86) and [UsersController#destroy](https://github.com/joshsoftware/code-curiosity/blob/master/app/controllers/users_controller.rb#L64)
IMO, we should:
1) add uniqueness check for uid 
2) avoid appending '-DELETED' to the user's uid. 
3) Add a field 'deleted_at' which takes a timestamp when the user deletes the account. Use this field to check status of an user.

**Comment by gautamrege** [comment]
Yup - This is the right approach. Earlier, we did not expect users to re sign-up and we wanted to ability to soft-delete users because of referential integrity. 

In addition to what you have mentioned:
+ The Royalty points should be re-calculated if the user signs up again, since people delete, move, transfer repos.
+ The transactions (especially the redemptions ones) should be checked and adjusted against the new royalty points as required. So, if a user had redeemed 500 points, then deleted the account and re-signed up, the re-calcualted royalty points should deducted by 500 points!

**Comment by prasadsurase** [comment]
@gautamrege [User#set_royalty_bonus](https://github.com/joshsoftware/code-curiosity/blob/master/app/models/user.rb#L166) creates a transaction of type 'royalty_bonus' on user signup. Say, a user deletes and re-signups, this again creates another transaction. Should there be exactly one instance of a royalty_bonus for a user irrespective of the number of times a user deletes and signs up?

**Comment by gautamrege** [comment]
No. There can be more. But they should only be the positive delta. 

For e.g.  A user signs up today and gets 350 royalty points. In one year he has earned 1000 points and redeemed 250. After an year he deletes his account. After another month he signs up again. New his royalty points calculated are 450. So, on re-sign-up, we should reactivate his account (along with all past history and transactions) but add only the delta of royalty points i.e. 100 points. 

Note: admin should be able to permanently  delete an account. This is real delete and not a flag. 

- Gautam
Sent from my iPhone

www.joshsoftware.com
