### ISSUE TITLE
Commits didn't get pulled

### ISSUE THREAD

**Issue by sivagollapalli** [joshsoftware/code-curiosity#210]
I made commits on Nov 17th, 2016. Comments made on that day got pulled but commits didn't pull. 

Here is my PR`https://github.com/mongoid/mongoid-history/pull/180/commits`

**Comment by prasadsurase** [comment]
The commit made by the author is associated with the help of email address specified in the local git settings. These details(user name and email) are sent in the commit header to Github. The local git settings can be viewed by `git config --list`. 

  The commits are not listed because they're not associated with you git account since your local git settings don't have an associated email address. Refer [this](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user) link for more details.

**Comment by sivagollapalli** [comment]
To rewrite git history follow `https://help.github.com/articles/changing-author-info/`. Once commit get associated with email ID it will get pulled.
