### ISSUE TITLE
Contribution to DuckDuckGo Not showing

### ISSUE THREAD

**Issue by gautamkrishnar** [joshsoftware/code-curiosity#233]
I am an active DuckDuckGo contributor with merge access to all the DDG repos. My contributions are not listed on my profile!

Profile link: https://codecuriosity.org/users/gautamkrishnar

Its better if it get counted too...

**Comment by prasadsurase** [comment]
@gautamkrishnar Your activities for DDG are retrieved and listed on your dashboard. As for commits, you have merged 9 PRs against DDG/zeroclickinfo-goodies's master branch on 25th Dec. They aren't listed because Github doesn't list these as your commits in your fork. Github lists commits for an author if he/she has added them on his/her own repository(or a fork, or on repositories that belongs to the organization the author owns). Incase if you want to list the MERGE commits for any of DDG repositories, you need to be owner of DDG.

**Comment by gautamkrishnar** [comment]
@prasadsurase thanks for the information 😄
