### ISSUE TITLE
Commits in branch other than master don't show up

### ISSUE THREAD

**Issue by anshuman73** [joshsoftware/code-curiosity#236]
I made a few commits - https://github.com/metabrainz/musicbrainz-server/commit/5fbdfbcb125e558d7c2a2caa7146a4e3cb95b169

that don't show up on my code curiosity page even after multiple refreshes. This can be extremely harmful for someone trying to complete their monthly goal.
@gautamrege 

![screenshot from 2017-01-01 13-26-58](https://cloud.githubusercontent.com/assets/12889549/21580568/72bb78ca-d026-11e6-8359-ff30009b79ca.png)

**Comment by sethu** [comment]
@anshuman73, the issue was that while getting list of branches it by default list first 30. In this case, this repo has 70 branches and your commit was above 30 so it got missed. Fix is done, but last month(December) scoring is already done and can't re-scored. We will see if we can add some bonus points.

**Comment by anshuman73** [comment]
Nice to hear fix has been implemented.
Thanks !
It'd be nice if you could add the bonus points :)

**Comment by amitk** [comment]
@anshuman73 This issue is already been fixed. So, please close this issue.
