### ISSUE TITLE
Kindly See to the request for the coupon code in exchange for points

### ISSUE THREAD

**Issue by Princu7** [joshsoftware/code-curiosity#246]
@prasadsurase @sethu 
I am really sorry to bother about this issue in this manner. I tried sending emails but received no replies. 9 Days ago, I made a request for a coupon code in exchange for 250 points. There was no response. I again send a mail regarding this delay about 5 days ago but there was no response on that one too. This is really disappointing and saddening as a contributor. Please look into this issue and provide a solution. Thank you so much.

**Comment by sethu** [comment]
Your request was redeemed and don't be disappointed if you are really interested in contributing to opensource.

**Comment by Roshanjossey** [comment]
@Princu7: Could you please confirm if your request was redeemed? I believe such customer relationship is an important factor.

@sethu: It's not about intention. It's about codecuriosity. I don't think @Princu7 took the trouble to come here and raise an issue because he wanted a coupon. He wants to improve codecuriosity itself. If somebody mails to info@codecuriosity.com, it's only fair that they get a reply. that's the customer relationship people expect from a product. I think feedbacks like this should be treated with seriousness.

People might not stop contributing because of this. But they might stop using codecuriosity. Do you really want that?

**Comment by Princu7** [comment]
@Roshanjossey @sethu Thanks for the help. My request was redeemed and I have received a coupon code for redemption. I love open source and contributing to it. Code Curiosity is like an extra cherry on top of it. Who doesn't getting like getting some reward for his work? CC is a great piece of software which acts as a stimulus for someone who is just starting out into the world of open source and I am really greateful for it. When I didn't received a reply, I was a bit disappointed and so would have been anyone else. That's why I created an issue here. No other intentions. Thanks for this platform.

**Comment by Roshanjossey** [comment]
@Princu7: Thanks for confirmation. Keep up the good work

**Comment by sethu** [comment]
@Roshanjossey, I hope you read @Princu7 full comment and read my reply to that context.

For your clarity, codecuriosity itself a opensource system and support by community and we put in our own money. We aren't running 24x7 support.

See, if you can help in marketing  codecuriosity and get some subscribers  who will be regularly sponsoring the redemption points.

Keep contributing.

**Comment by Roshanjossey** [comment]
@sethu, Yes I had read the whole discussion thread before commenting.

I know the constrains and I'm just stating that support can be improved. I for one have never gotten any replies when tried to contact info@codecuriosity.com.

I do market codecuriosity among my professional and friend circles. I believe its a brilliant initiative and it lives up to its promises
