### ISSUE TITLE
after redeem point not getting code 

### ISSUE THREAD

**Issue by jsroyal** [joshsoftware/code-curiosity#277]
After getting first-time offer code from redeeming point but in second time not getting any offer code.
Also, it has been a long time.
![screenshot from 2017-05-12 17-55-20](https://cloud.githubusercontent.com/assets/10773353/25997947/52bd8df6-373c-11e7-9f05-955c497912c6.png)
contact through the mail does not response why am I not getting offer code.

**Comment by Princu7** [comment]
@jsroyal You are not alone in this. I and my friend also tried redeeming points in the starting of this month but there has been no response from Code Curiosity site on this. We also tried emailing the support staff of the Code Curiosity team for this issue but didn't get any reply. Let's hope this gets resolved soon and turns out to be a temporary problem. This is a terrific platform and I would really hate for it to go down.

**Comment by ferbncode** [comment]
any progress on this? I tried redeeming some points in the starting of May. However, I did not receive the coupon code yet. I emailed the support staff regarding the delay of the coupon code but received no response. I suppose this is a temporary issue and would be resolved soon. Thanks for such a great platform for supporting open souce contributions. 🙂

**Comment by sethu** [comment]
Thanks for your hard work. It's the very intent of CodeCuriosity to motivate the push towards open source contribution. 
Regarding your redemption request, hang in there. We're on it but please do realize that this money comes out of our own pocket. So, bear with is for just a while.

**Comment by jsroyal** [comment]
Sorry @sethu sir for creating this temporary issue but I think if somebody else has in the same then inform them it is common for everybody.
Thank you for inform us.
I think now everybody gets it.
>bear with is for just a while.

Sure Sir.
It is very nice to invent to push us for contributing to open source.
Thanks, Codecuriosity.
I mean this is not more issue.
