### ISSUE TITLE
Not all contributions show up

### ISSUE THREAD

**Issue by chashmeetsingh** [joshsoftware/code-curiosity#377]
I had contributed to a no. of repos from May - August and not all contributions had synced up at that time for a particular repo when I had created an account hence, didn't receive points for the same.

Repo: https://github.com/fossasia/susi_iOS

**Comment by amitk** [comment]
@chashmeetsingh this repository [ https://github.com/fossasia/susi_iOS](url) belongs to an organization and CodeCuriosity don't fetch commits of repository belonging to an organization.

**Comment by amitk** [comment]
@chashmeetsingh Your problem is resolved, now susi_iOS repo is synced with CodeCuriosity. 
The reason for your contributions not getting synced with CodeCuriosity is that, at that time these repos must have stars less than the minimum no. of stars, a repository required to get synced with CodeCuriosity.
