### ISSUE TITLE
Royalty Bonus

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/code-curiosity#45]
When a user signs up, we analyse the profile and calculate the Royalty Bonus score. 

* This is **only** for repository that the user owns that have more than 50 stars. Repositories that the user contributes as part of organisations or other user profiles are **not** counted for this.
* The royalty factor depends on the user followers too! More followers means higher royalty bonus factory for each popular repository.

For example, user "jiren" owns 2 repositories "filterjs" and "streamable" that have 442 stars and 363 stars respectively. He also contributes to "rails/rails".  He has 35 followers. 

### Royalty for users
[stars for filterjs] + [stars for StreamTable]

(442 * 100  +  363 * 100) *  (60 / 100) =  65,980 points.

The equation: 
SUM [ (stars * 100) ]  * (followers / 100)

Caveat: If the royalty calculation comes over 500k points, show the message: "You're way over the top - contact the team and we shall work out a fixed income per month for you ". 

These users are already celebrities and CodeCuriosity is not for them. In such cases, rather than have the person participate monthly, we involve the person in making CodeCuriosity better product. If we get enough grants / funds or money, we would love to reward such stalwarts! 

*We shall improvise the process over time*

**Comment by spidergears** [comment]
@gautamrege A small correction in the calculations 
[stars for filterjs] + [stars for StreamTable]

(442 * 100 + 363 * 100) * (60 / 100) = 48,300 points.

Also, by followers do you mean, the followers of the repository owner or the number of watches on the repository? 
Since we are multiplying the score from stars by a factor of (followers/100), this diminishes score until the user get 100+ followers and only begins to go up once the number of followers goes above 100. This doesn't sound good for small time contributors with less(<100) followers.
Is this intended?

I would suggest we add these up and not multiply,  `SUM [ (stars * 100) ]  +  (followers / 100)`
In case you want keep the scores low, the multiplication can be smaller.

**Comment by jiren** [comment]
@spidergears I have changed criteria of repos stars to minimum 25. 
Formula is

`((repos_star_count)*100) * ([followers, 100].min/100.0)`
