### ISSUE TITLE
In redeem popover points and cash misplaced

### ISSUE THREAD

**Issue by aashutoshrathi** [joshsoftware/code-curiosity#464]
## In the redeem popover, it asks for points but accepts dollar to be redeemed.

![image](https://user-images.githubusercontent.com/21199234/42134173-e7d8c5d2-7d53-11e8-9abf-288186d13f61.png)

**Comment by pratik14** [comment]
hey @aashutoshrathi, it is actually Redeemable amount. Thanks for pointing out, will change it soon.

On profile page:
Points: is total points you earned till now
Earned: Amount debited to your account
Redeemable: Amount you can redeem. 

Points you have earned before  1 July, 2018 will not be redeemable.

**Comment by tcNickolas** [comment]
@pratik14 "New redemption strategy" email actually said "If you had sent a redemption request, we shall return all these points to you." So what is it - previously ignored redemption requests (see #385) will be just discarded, or will these points be returned? It would be very nice to have a uniform message about this across all methods of communication.

**Comment by pratik14** [comment]
Hey @tcNickolas there has been change in redemption process. These were the issue we were facing

- A few people get a larger piece of the rewards.
- Redemption happens in chunks of 10$
- Redemption can only be done after the month is over!
- Redemptions have been delayed because of reviews, fund shortage and time!

 So we came with new process(You can check the details in email)

**Basically,** 
 - All the previous redemption request are discarded. 
 - Contribution which are done after 1 July, 2018 will be rewarded.
