### ISSUE TITLE
Activity didn't get pulled

### ISSUE THREAD

**Issue by sivagollapalli** [joshsoftware/code-curiosity#61]
Recently I have added an issue and a PR to https://github.com/proton/mongoid_auto_increment/pull/10 . But on code curiosity, the issue get pulled but my contribution didn't get pulled. PFA

![issue](https://cloud.githubusercontent.com/assets/280199/16906496/801d6a9c-4cd6-11e6-86f2-40373404b795.png)

If you see the screenshot, on 14/07/2016, there is an issue but there is no contribution though my contribution did on 12 July 2016.

**Comment by gautamrege** [comment]
Working on this.

**Comment by sivagollapalli** [comment]
@gautamrege Looks like activity gets pulled but points didn't get updated. If I count manually I get 22 points whereas on the widget it shows 20 points.

**Comment by gautamrege** [comment]
@sivagollapalli Please check -- I see that you have 24 points and all commits and activities are reviewed and scored in the current round. I am adding a button for "Sync" in your Contributions tab in case you don't see some commits and activities available.

**Comment by amoludage** [comment]
Same happened with me the [issue](https://github.com/stympy/faker/issues/638) get pulled but my [contribution](https://github.com/stympy/faker/pull/639) didn't get pulled.

**Comment by gautamrege** [comment]
@amoludage @sivagollapalli I think your problem is solved. 

I have added the "Sync" functionality on the "Contributions" page that can pull in any commits & activities that may have been missed for any reason. This works for the current round only! Please check.

@pramodshinde let me see what I can do about your problem.

**Comment by Shwetakale** [comment]
@gautamrege Same with my account. For last round points are calculated but not credited for that month and activities for last day i.e.(30th June) are counted in July.

**Comment by sivagollapalli** [comment]
@gautamrege No flash message, when I click on `sync` button. Also, I am not able to  see repositories tab in the sidebar. Is that intentional or it's a bug?
![sidebar](https://cloud.githubusercontent.com/assets/280199/17164790/21c0a5b2-53e9-11e6-8130-4d534583eb4c.png)

**Comment by gautamrege** [comment]
@sivagollapalli There is no point in showing repositories now as we track all contributions to relevant repositories (> 25 stars).


Closing this issue for now, since @apsc92 helped fix the cosmetic issues. 

Also, the points should be syncing now -- incase you see the points credit issue again ion the future, please re-open this issue.
