### ISSUE TITLE
How the commit score is calculated? 

### ISSUE THREAD

**Issue by nixmaniack** [joshsoftware/code-curiosity#93]
Just wanted to understand how the commit score is calculated. Is there any document for this explanation?

Do the PRs which are cherry-picked by the Maintainers of the project get any score? Or just the PRs which are merged get scored?

**Comment by gautamrege** [comment]
Glad you have asked this question. I hope the discussions that ensue here, improve the scoring as much as possible! 

@nixmaniack The entire logic for scoring in the file `app/models/scoring_engine.rb`. Feel free to help us improve it. We use a combination go bugspots and our own logic to get a score. 

Scoring is not done on PR but on commits. So, even if the PR is not accepted, you still get points since the commits are scored. The reasoning behind this was that when it takes a sizeable amount of effort even commit code and send the PR - that effort is rewarded. The PR getting accepted or not is considered.

**Comment by nixmaniack** [comment]
Thanks for the explanation. I'll go through the score engine.

The reason for asking this was, I've only got points on `comments` and never on `commits`. The project I contribute to doesn't do `merge` but they do cherry pick the code.

**Comment by gautamrege** [comment]
Nah! It's nothing to do with cherry-pick and merge.. The commits are in your "Contributions" tab. What I shall try and do is check with the bugspots code and see why you are getting a 0 score. Basically, I will test out the scoring engine with your commit. 

I will update this comment .. hopefully we find something that can help improve the scoring engine 😄

**Comment by gautamrege** [comment]
Closing this as this has been raised under Documentation issue #105 We shall document everything properly.

**Comment by pranavgore09** [comment]
JFYI, I just discovered that my commit points are 0 since last 8 months :smile:  and definitely, I made significant commits to repositories having 25+ stars! (if that's still a rule)
I haven't gone through the code but I thought to write it here if that helps.
Thanks for all your hard work!

**Comment by gautamrege** [comment]
We'll take a look at your ID. 

- Gautam
Sent from my iPhone

www.joshsoftware.com
